### ISSUE TITLE
No sound from headphones after one or two songs

### ISSUE THREAD

**Issue by stupidus89** [enricocid/Music-Player-GO#32] opened 2018-07-02 20:03 UTC
I started using Music Player Go on my Sony Xperia XZ1 Compact running LineageOS 15.1 and I am repeatedly running into the following problem:

- I start playing an album
- At the end of the first or second song, suddenly there is no more sound coming from the headphones
- However, the app shows the next song still playing (not in paused state)
- In order to get sound again, I need to unplug and replug my headphones

I can rule out an hardware issue, as the headphones are working fine both on other devices as well as with the stock Lineage Music app. Also, the fact that the sound always stops on a song change suggests that it is a software issue. Is Music Player Go using some audio API that is different from the one that the stock music player uses?

**Comment by enricocid** [comment] 2018-07-02 20:22
The player uses media player implementation. I don't known, I always test the release on pure android, maybe there are problems on OEMs android versions. I need a logcat to understand:)

**Comment by kvsjxd** [comment] 2018-07-03 04:33
I can't reproduce this bug on my device

**Comment by enricocid** [comment] 2018-12-02 19:02
closing as implementation will change on kotlin releases

**Closed by enricocid** 2018-12-02 19:02 UTC
