### ISSUE TITLE
[FR] "Pause on completion" BY DEFAULT

### ISSUE THREAD

**Issue by JapanYoshi** [enricocid/Music-Player-GO#433] opened 2022-06-23 14:27 UTC
1) **Describe the solution you'd like**

Do not reset the settings to "pause on completion off" every time I play an audio file. If I want the app to play other random songs, I WILL TELL THE APP TO DO SO.

2) **Describe alternatives you've considered**
na

3) **Additional context**
na

**Comment by enricocid** [comment] 2022-07-02 08:51
Ok.

PS alternatives are not other apps but other approaches to the problem:)

**Comment by enricocid** [comment] 2022-07-06 13:22
Pause on end is already persisted. So, can't understand what the issue is.

In my tests the mode get restored properly and mantained even when playing new songs...

**Comment by JapanYoshi** [comment] 2022-07-07 00:21
Android 11 on Oppo Reno 3a.

**Comment by enricocid** [comment] 2022-07-08 09:05
Could you try the debug apk from this action once built? I've added a toggle to control pause on end...

https://github.com/enricocid/Music-Player-GO/actions/runs/2635069492

Let me know.
Thanks

**Comment by JapanYoshi** [comment] 2022-07-14 14:47
I just opened an M4A audio file from the File Manager app. Music Player Go IGNORED THE TOGGLE SWITCH and started playing other audio files from the same folder.
![Screenshot_20220714_234617](https://user-images.githubusercontent.com/8707990/179010544-bdf0eca1-244c-41fc-a518-2a2da12844d6.png)

**Comment by enricocid** [comment] 2022-07-14 14:50
try the latest build

https://github.com/enricocid/Music-Player-GO/actions/runs/2663882676

**Comment by JapanYoshi** [comment] 2022-07-14 15:24
`That seems to prevent the next song from playing, *until* I seek to any point in the file after it finishes playing. When I release the finger, it loads a different file and starts playing it from the start.

Maybe it’s just not worth ditching VLC for now.
`

**Comment by enricocid** [comment] 2022-07-14 16:15
Try this
https://drive.google.com/file/d/13S4mk_N7LaBBJtlDlh6I7RiHUqThe9Zi/view?usp=sharing

**Comment by enricocid** [comment] 2022-07-15 18:05
The recent changes fixed the issue in my tests. Closing.

**Closed by enricocid** 2022-07-15 18:05 UTC
Labels: feature request
