### ISSUE TITLE
Open music from outside the app (Intents)

### ISSUE THREAD

**Issue by contrapunctus-1** [enricocid/Music-Player-GO#55] opened 2018-12-15 15:15 UTC
It'd be nice if Music Player GO was offered for opening audio and video files e.g. from file managers (in the latter case it could just play the audio stream.)

**Comment by enricocid** [comment] 2018-12-15 15:19
I already implemented this feature, and I will release as soon as but I will be able to improve the implementation😉

**Comment by gsrathoreniks** [comment] 2019-07-29 20:32
Just wondering wether this issue has been resolved or not, as you said you already implemented but the issue is still OPEN.

**Comment by enricocid** [comment] 2019-07-30 08:26
the feature is coming soon :) just need to fix some things

**Comment by enricocid** [comment] 2019-07-30 12:18
Fixed. It will be included in next release

**Closed by enricocid** 2019-07-30 12:18 UTC
Labels: enhancement, feature request, good first issue, wip

**Comment by contrapunctus-1** [comment] 2019-07-30 14:54
Thanks! Re: videos, can't it just play the audio stream?

**Comment by enricocid** [comment] 2019-07-31 06:13
I don't know, gonna investigate🕵️‍♂️
