### ISSUE TITLE
[BUG] For songs without a cover: no navigational buttons drawn except play/pause

### ISSUE THREAD

**Issue by sycam0r-e** [enricocid/Music-Player-GO#365] opened 2022-02-01 14:17 UTC
1) **Describe the bug**
When I start playback of music, there are no buttons drawn for pausing, fowarding, playing etc. both on the lock screen and in the notification centre. Note that a touch to the area does produce the intended action though.

2) **To Reproduce the behaviour**
   1. Play any music track.
   2. Pull down to see notification centre or lock phone to see lock screen.
   3. See error!

3) **Expected behavior**
The navigation buttons should be displayed.

4) **Smartphone**
 - Device: Pixel 4a
 - OS: Android 12
 - ROM or mods: GrapheneOS Build SQ1.220105.002.2022013120
 - MusicPlayerGo version: 4.412

5) **Screenshots**

<img height="450" src="https://user-images.githubusercontent.com/98783999/151985121-045010b5-9245-47d1-a143-45afea95fed7.jpg"><img height="450" src="https://user-images.githubusercontent.com/98783999/151985176-68be9c00-60b6-4676-bbd8-7d609cc3da3f.jpg">

**Additional context**
 - The error persists across phone restarts and across GrapheneOS updates. 
 - I _think_ it started with the MusicPlayerGo version that introduced the new dark theme which led to #350 but I am not certain. 
 - I am using MusicPlayerGo in a user profile, which hasn't led to any problems so far.

**Comment by enricocid** [comment] 2022-02-02 07:57
Hi, thanks for letting me know.

Could you try disabling album covers option and see what happens?

What happens if you click where the actions should appear?

**Comment by enricocid** [comment] 2022-02-02 11:07
So actions are invisible even with embedded covers are disabled?

Yeah, weird issue. Everything works good on aosp emulator.

Gonna investigate the issue. Will post test apk in the future.

Sadly I don't have a device running android 12 and can't reproduce this issue, so I need You to test changes 😊

**Comment by division4** [comment] 2022-02-02 11:11
> So actions are invisible even with embedded covers are disabled?

Yes. Additionally, the cover is still visible, not sure whether this is intended.

> Sadly I don't have a device running android 12 and can't reproduce this issue, so I need You to test changes 😊

Sure thing, I'm happy to help! Thanks for your work! :)

**Comment by enricocid** [comment] 2022-02-02 11:29
Thank you!

Notifications not updating is another bug. Shame on emulators😂

Could you test builds from here?

https://github.com/enricocid/Music-Player-GO/releases

4.4.12 and 4.4.11

Be sure to disable battery optimization 😊 Thanks.🙏🏻

**Comment by division4** [comment] 2022-02-02 12:03
I tested both with disabled battery optimization. The bug persists.

**Comment by enricocid** [comment] 2022-02-04 11:41
Hi, could you check if this player works?

Thanks

https://github.com/OxygenCobalt/Auxio

@OxygenCobalt

**Comment by division4** [comment] 2022-02-08 13:39
I checked: it doesn't work, the buttons are not drawn.

**Comment by OxygenCobalt** [comment] 2022-02-11 03:22
Seems like a system-specific issue. I've had situations where the system UI permanently messes up it's UI for whatever reason and the only way to fix it is to factory reset the OS.

**Comment by enricocid** [comment] 2022-02-11 07:47
Yep, that's a weird bug.
I'm copying & pasting the code for notifications directly from Google guidelines...

I've noticed, for example, that switching profiles on Android 10/lineage os causes system UI to draw status bar over the toolbars and other UI issues...

**Comment by division4** [comment] 2022-02-11 15:49
I tend to agree. 

(I fairly recently did a factory reset (for other reasons, the bug issued here happened at some point after the reset). I didn't manipulate any permissions or sys settings though that were temporally close to the emergence of this bug so I have no clue.)

I won't factory reset in the near future. When I do, I will observe how MusicPlayerGo (and Auxio) behave and will report.

Feel free to close this issue in the meantime or let me know if there is anything else I can test. :) Thanks for your time and work! :)

**Comment by flippflapp** [comment] 2022-10-10 19:57
Interesting development:

My OS (GrapheneOS) has been on Android 13 for a while now (but not when this issue started).

I just updated Music Player GO to 4.4.22 which implements support for Android 13.

Now, the navigation buttons _are_ drawn everywhere, BUT if a song does not have a cover, only the play/paus button is drawn. 

Note that I did not factory reset my phone in the meantime.

Does this crack the riddle?

**Comment by OxygenCobalt** [comment] 2022-10-10 19:59
Can you show a screenshot @flippflapp?

**Comment by OxygenCobalt** [comment] 2022-10-10 20:08
Ah, that's not an issue with the system UI, MPGO is simply uploading a default cover that makes the color calculation not work properly.

@enricocid You may want to stop providing your default cover icon to the notification and simply pass `null` to `METADATA_KEY_ALBUM_ART`/`setLargeIcon`

**Comment by OxygenCobalt** [comment] 2022-10-10 20:09
Otherwise, I think we can close this issue since it's resolved on GrapheneOS's end.

**Comment by flippflapp** [comment] 2022-10-10 20:10
Let me know if you want me to test a test-apk.

**Comment by enricocid** [comment] 2022-10-10 20:17
@OxygenCobalt Already doing 😆

https://github.com/enricocid/Music-Player-GO/blob/0a40c107865e1b3f65cfa2f12c893e158bd6c4bd/project/app/src/main/java/com/iven/musicplayergo/extensions/MusicExts.kt#L97

**Comment by flippflapp** [comment] 2022-10-10 20:20
No idea whether this is related, see #477 which I just filed.

**Comment by enricocid** [comment] 2022-10-10 20:25
Yes, there's something wrong in that extension 😆 I'll post an apk later (sorry, but I still don't have A13 running on my device, only emulator which is working good)

**Comment by flippflapp** [comment] 2022-10-10 20:26
No worries at all, don't stress! Thanks so much for your work! :) Just ping me when you have an apk and I'll test it (probably tomorrow).

**Comment by flippflapp** [comment] 2022-10-13 11:39
Sorry if I was unclear, but the test-apk over [here] did not this this issue :(

**Comment by enricocid** [comment] 2022-10-13 11:54
Could you post me some screenshots?
1) Cover option disabled
2) Cover option enabled (but no cover available)
3) Cover option enabled (cover available)

Thanks :)

**Comment by enricocid** [comment] 2022-10-13 12:43
[setColor](https://developer.android.com/reference/androidx/core/app/NotificationCompat.Builder#setColor(int)) and [setColorized](https://developer.android.com/reference/androidx/core/app/NotificationCompat.Builder#setColorized(boolean)) set to true is probably causing the issue @OxygenCobalt 
`null` is already passed on error/cover option disabled

@flippflapp 
Test apk:
https://drive.google.com/file/d/1bLgg6SJog2yNMvyIRllcgbu3WI3bGqT4/view?usp=sharing

**Comment by flippflapp** [comment] 2022-10-13 13:25
@enricocid the bug persists:

1. Cover option disabled (cover available):
<img height="450" src="https://user-images.githubusercontent.com/98783999/195608347-87e89b31-3ee9-4119-b848-5fd0b8e0801e.png"> <img height="450" src="https://user-images.githubusercontent.com/98783999/195608356-4d63aeb6-b31d-4316-91dd-72e66fb7c8e1.png">

2. Cover option enabled (but no cover available)
<img height="450" src="https://user-images.githubusercontent.com/98783999/195608360-6d62262e-6cce-4234-af36-8102fb47012b.png"> <img height="450" src="https://user-images.githubusercontent.com/98783999/195608367-1aea7991-2bed-4b4d-9e14-0788c320219c.png">

3. Cover option enabled (cover available)
<img height="450" src="https://user-images.githubusercontent.com/98783999/195608370-0bb89df5-1d84-4c91-b8f1-c7981bd3343b.png"> <img height="450" src="https://user-images.githubusercontent.com/98783999/195608379-d6e2eab8-21f7-4cdf-90d9-d4495eebd4f9.png">

**Comment by OxygenCobalt** [comment] 2022-10-13 16:20
@enricocid Yeah, `setColorized` isn't really meant to be used for notifications.

**Comment by OxygenCobalt** [comment] 2022-10-13 16:28
That is basically the bitmap loading routine I use @enricocid. Looks fine.

**Comment by enricocid** [comment] 2022-10-13 16:35
I'd wipe the entire Android ecosystem with a flamethrower xd

**Comment by flippflapp** [comment] 2022-10-13 17:05
The bug persists.

**Comment by enricocid** [comment] 2022-10-14 07:21
Do you know of any open source music player working flawlessly?

For example, have you tried [Auxio](https://github.com/OxygenCobalt/Auxio) or the new [Shuttle](https://play.google.com/store/apps/details?id=com.simplecityapps.shuttle)?

Thanks.

**Comment by enricocid** [comment] 2022-10-14 20:25
@flippflapp 

New test apk :)

https://drive.google.com/file/d/1IezegSWb8e5eIr4Lf0gX-WWTdcfrMxUw/view?usp=sharing

**Comment by sycam0r-e** [comment] 2023-11-11 11:11
@enricocid 

Sorry for not getting back to you. I think that test apk didn't change the bug back then.

In the meantime, I migrated to a factory new smartphone with a fresh install of the OS and of MusicPlayerGo.

    Device: Pixel 8
    OS: Android 14
    ROM or mods: GrapheneOS Build UD1A.231105.004.2023110700 (latest stable version)
    MusicPlayerGo version: 4.4.23

The bug persists. Behaviour is as described [here](https://github.com/enricocid/Music-Player-GO/issues/365#issuecomment-1277611797), i.e., for songs without a cover, no navigational items are drawn except the play/pause button (also no display of the song name) but touching the area produces the correct action.

Let me know if I can help!

**Comment by sycam0r-e** [comment] 2024-05-07 11:50
@enricocid I am happy to report that the bug just disappeared after an OS update some weeks ago. Thank you for your patience and help with this issue, and thank you tonnes in general for the maintenance of this project! ❤️

**Closed** 2024-05-07 11:50 UTC
Labels: bug, help wanted

**Comment by enricocid** [comment] 2024-05-08 15:50
Thanks 😁
