### ISSUE TITLE
Audio not playing and Time incorrect

### ISSUE THREAD

**Issue by seventhsonmizo** [enricocid/Music-Player-GO#110] opened 2020-01-07 15:38 UTC
Audio not playing and the time for any audio is not displaying properly. Everything is fine at the emu but testing on the real phone.. 
![Screenshot_2020-01-07-21-06-14-212_com iven musicplayergo](https://user-images.githubusercontent.com/51083588/71907334-d0b89c80-3191-11ea-8c4e-b503fe1ca294.jpg)

**Comment by enricocid** [comment] 2020-01-07 15:47
Hello,
thanks for reporting. Would You mind sharing device, android version and an audio sample? Thanks

**Comment by seventhsonmizo** [comment] 2020-01-07 16:31
I am testing on Xiaomi Mi 8SE, running AndroidX

**Comment by seventhsonmizo** [comment] 2020-01-07 16:32
All audio is not playing.. any type.. m4a, mp3..etc.

**Comment by enricocid** [comment] 2020-01-07 16:33
Need a logcat then :)

**Comment by enricocid** [comment] 2020-01-07 16:57
I still don't have Android 10 and afaik there could be problems with scoped storage. Could You try this?

https://drive.google.com/open?id=1_8iOCDjy5UV-OZw7xYYm1FC9GDu8_yJJ

**Comment by seventhsonmizo** [comment] 2020-01-07 17:13
Yes..this is working. Any change on source code?

**Comment by enricocid** [comment] 2020-01-07 18:04
I added 

`android:requestLegacyExternalStorage="true"`

to the app's manifest to temporarily opt out scoped storage.
Source: https://developer.android.com/training/data-storage/compatibility

In build.gradle I added 

```
lintOptions {
    disable 'UnusedAttribute'
}
```

to disable the lint warning (attribute is only used in api 29)

**Comment by seventhsonmizo** [comment] 2020-01-08 04:28
It works now by adding those codes. But the volume is low. Maximum volume is like 50% of the volume from my default music player.

Sorry for late reply...I can only check out at night due to my works..
I will continue at evening

**Comment by enricocid** [comment] 2020-01-08 12:23
No problem. Thanks for reporting. I will be able to tackle the volume issue as soon as I receive Android 10 on my Mi A2 lite :)

**Comment by enricocid** [comment] 2020-01-08 12:46
I added an option to disable precise volume control. Let me know if the problem if disabling volume control fixes the issue

https://drive.google.com/open?id=16hcFxDVVIhcJ6DO-xJ6_8uv5PUqibKvd

I will rework this feature once I receive android 10

**Comment by seventhsonmizo** [comment] 2020-01-10 05:00
Yup.. this apk works great now.

**Comment by seventhsonmizo** [comment] 2020-01-10 05:03
Please update me the changes when you ready..

**Comment by enricocid** [comment] 2020-01-10 13:02
Changes have been pushed :)

https://github.com/enricocid/Music-Player-GO/commit/be6abf17dc2231fb0b100ad1396540cf8418d9ac

**Comment by enricocid** [comment] 2020-01-10 17:11
Hi,

I've added back scoped storage, so I removed the attribute from manifest.
I replaced data with content uri, could you please let me know if it works properly so I can push the changes?

https://drive.google.com/open?id=1rpzBum63VZc0XyHEG1VZPYvPSjPvWpsK

Thanks

**Comment by pirhszm** [comment] 2020-01-12 14:06
Re: Isn't fetching songs... [from Play Store]

I have tried this debug apk and latest from Issue:105; in both cases app crashed after opening. 

If the issue isn't related to this one, I can open new.

**Comment by enricocid** [comment] 2020-01-12 14:18
send me a bug report if You can. Refer to this guide :)

https://developer.android.com/studio/debug/bug-report

**Comment by pirhszm** [comment] 2020-01-12 15:09
https://paste.ee/p/W7Ol5 Is it helpful?

**Comment by enricocid** [comment] 2020-01-12 15:12
Have you granted read external storage permission?

**Comment by pirhszm** [comment] 2020-01-12 15:13
yes

**Comment by enricocid** [comment] 2020-01-12 15:13
Ok, gonna send test APK soon :)

**Comment by enricocid** [comment] 2020-01-12 16:53
> yes

here you go: https://drive.google.com/open?id=12XI5YyJBWzYObp0d_lEJb_MMyiJ9JQ7_

**Comment by enricocid** [comment] 2020-01-13 09:39
> yes

This is the latest debug apk

https://drive.google.com/open?id=1B4Oe7ihoeDEDfS4ajqbP4kE5N3w5CaGO

**Comment by pirhszm** [comment] 2020-01-13 10:56
https://paste.ee/p/FJQ7T not working

**Comment by enricocid** [comment] 2020-01-13 13:15
> https://paste.ee/p/FJQ7T not working

Hello,
I've reviewed the permission request. Please let me know if the problem persists

https://drive.google.com/open?id=1JlMcJjC8ItmR1XtLE3KtTy09sJ-u9hM9

**Comment by pirhszm** [comment] 2020-01-13 13:47
https://paste.ee/p/SNcpI still no luck

**Comment by enricocid** [comment] 2020-01-13 14:03
> https://paste.ee/p/SNcpI still no luck

https://drive.google.com/open?id=1mJIi7j1BgqxelakvnkDBotYW_cwHfxgm

**Comment by pirhszm** [comment] 2020-01-13 14:18
https://paste.ee/p/m7JA6 - on first open

https://paste.ee/p/CVJ3N - on second open

**Comment by enricocid** [comment] 2020-01-13 16:46
https://drive.google.com/open?id=1bXhBZDXsbK3CUlI5aGJzFdxbSAzMIg_X

https://drive.google.com/open?id=1paXWOnwgcgURds4Uhqp_FDy6gYtfCwMJ

https://drive.google.com/open?id=1VU5S6UBurYzSqkTbu2SChbdYj51qiJCO

**Comment by pirhszm** [comment] 2020-01-14 05:48
None of them are working.. Haven't checked the logcat as I'm away from machine.

**Comment by enricocid** [comment] 2020-01-14 07:41
> None of them are working.. Haven't checked the logcat as I'm away from machine.

Send me a bug report as soon as you can. This time try to send be a complete bug report via developer options :) thanks

**Comment by enricocid** [comment] 2020-01-14 14:18
When you have time please try this :)

https://drive.google.com/open?id=1YaYlk_MSkhwcTfLz_dSKtkLDsXUj_TOt

Thanks

**Comment by enricocid** [comment] 2020-01-15 13:44
> None of them are working.. Haven't checked the logcat as I'm away from machine.

Hello,
I finally was able to reproduce the null pointer on android Q. Basically it was caused by music files in the root folder of the phone whose relative path was returning null.

Could you please confirm it is working now?

https://drive.google.com/open?id=1Onny90jLsrfxO0UbWBYU2hPNAIb0wB8I

**Comment by pirhszm** [comment] 2020-01-15 13:54
> Could you please confirm it is working now?
Yes, working.. thanks.

**Comment by enricocid** [comment] 2020-01-15 14:19
Closing then

**Closed** 2020-01-15 14:19 UTC

**Comment by enricocid** [comment] 2020-11-03 17:18
Hi guys.
I have never asked for donations as I don't really need.

This time I'm asking You a little effort.

### **If You liked my work and You want to manifest support for my project please consider to donate to a friend of mine who is living a very difficult situation (lost his job and the home).**

[gofundme page](https://www.gofundme.com/f/aiutarmi-per-favore)

Thanks
