### ISSUE TITLE
[bug] when I start the app, it crashes

### ISSUE THREAD

**Issue by joelocandol** [enricocid/Music-Player-GO#242] opened 2020-12-10 03:15 UTC
After I give access to the storage, the app crashes during loading screen 
Android: 7.0
Version: 4.3.4

**Comment by enricocid** [comment] 2020-12-10 08:08
Send me a bug report. Follow the instructions here :)

https://github.com/enricocid/Music-Player-GO/issues/236#issuecomment-735833154

**Comment by enricocid** [comment] 2020-12-12 19:02
Hi, I've released 4.3.5 version today. The update will be available within the next few hours. There was a library causing an issue on some devices. That library was replaced with a modern one so the problem should be fixed. Let me know if You still have problems. Thanks :)

**Comment by joelocandol** [comment] 2020-12-12 21:05
Hi, sorry for the late reply, but I didn't had access to the internet. The app stills crashes In the last update, but I already send to your email my bug report, hope it helps you.

**Comment by enricocid** [comment] 2020-12-12 21:42
> Hi, sorry for the late reply, but I didn't had access to the internet. The app stills crashes In the last update, but I already send to your email my bug report, hope it helps you.

4.3.5 still crashes?

**Comment by joelocandol** [comment] 2020-12-13 03:20
Yes

**Comment by enricocid** [comment] 2020-12-13 08:00
> Yes

Thanks.. then when the app crashes send a crash report using the send feedback button on the crash dialog, so I can read it directly from the Google console 👍🏻

**Comment by enricocid** [comment] 2020-12-13 13:08
Hi

From the report I'm reading

"Process: com.iven.musicplayergo, PID: 14357
java.lang.RuntimeException: Cannot initialize effect engine for type: 0634f220-ddd4-11db-a0fc-0002a5d5c51b Error: -3
12-09 22:53:21.566 14357 14357 E AndroidRuntime: 	at android.media.audiofx.AudioEffect.<init>(AudioEffect.java:411)
12-09 22:53:21.566 14357 14357 E AndroidRuntime: 	at android.media.audiofx.BassBoost.<init>(BassBoost.java:94)
...
12-09 22:53:21.566 14357 14357 E AndroidRuntime: 	**at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)**"

Are You applying some mods using xposed? I'm seeing crashes also in other apps.

If You are applying audio effects or some mods using xposed then consider to disable them as they clash with audio effects in MPGO.
There's no much I can do.

Let me know :)

**Comment by enricocid** [comment] 2020-12-13 14:40
Hi,

I think I have found a solution.

I'm going to post an apk soon. :)

**Comment by joelocandol** [comment] 2020-12-13 16:23
Thanks

**Comment by enricocid** [comment] 2020-12-13 21:14
Let me know if this one works

https://drive.google.com/file/d/1Kvniay8UBTcaZrqLTch3jNjXz3hx9MVD/view?usp=sharing

The crash seems due to the fact You already have a system equalizer and I'm trying to initialize the built in equalizer. 
Let me know if it works.

It's a debug apk, so You have to remove the one installed from f-droid/playstore.

**Comment by joelocandol** [comment] 2020-12-14 03:52
Yes, this version work without problem 👍 thank, man

**Comment by enricocid** [comment] 2020-12-15 16:10
Hi, 
I have released 4.3.6 to PlayStore.
Let me know if the problem is solved. If yes, You can close this issue :)

**Closed** 2020-12-17 00:34 UTC
