### ISSUE TITLE
The player UI gets reset everytime the smartphone is rotated

### ISSUE THREAD

**Issue by twisteros** [enricocid/Music-Player-GO#336] opened 2021-11-22 20:48 UTC
1) **Describe the bug**
Every time I rotate the phone to portrait or landscape the first tab gets active. 
If the Folders tab is playing a song the app also goes to the root folder under that tab.

2) **To Reproduce the behaviour**
1. Go to the Folders tab
2. Go into one of the folders and play a song

![image](https://user-images.githubusercontent.com/18228956/177270410-8b4c504f-aac4-46f7-8f87-8b6ccec44973.png)

3. Switch to Settings 

![image](https://user-images.githubusercontent.com/18228956/177271334-3a65318b-69d3-4467-9074-edeabca3004f.png)

4. Rotate the phone
5. Observe the first tab being activated and the file list changed to root

![image](https://user-images.githubusercontent.com/18228956/177270477-9e935bb5-e283-42c2-b9ef-0e85ba5425be.png)

3) **Expected behavior**
The active tab, the Folders tab content and the current UI state should be preserved during rotations

Android 11

**Comment by enricocid** [comment] 2021-11-24 12:15
Android version?

**Comment by twisteros** [comment] 2021-11-24 12:18
> Android version? grin

11 :)

**Comment by Knusper** [comment] 2021-11-24 15:28
Even worse, when rotating the current track starts playing from the beginning.

**Comment by enricocid** [comment] 2021-11-24 18:16
@Knusper can't reproduce on Android 10. Works fine for me.
What is your android version?

**Comment by Knusper** [comment] 2021-11-24 18:51
10 as well. Moto g7 power.

**Comment by Knusper** [comment] 2021-11-24 18:56
Ok ... I can't reproduce when I play something from the library. But when I
open a mp3 file with the file manager "open with" and play it - then
rotation starts playing again from the start.

**Comment by enricocid** [comment] 2021-11-24 18:57
Thanks, that's important information. Gonna fix asap!

**Comment by cardcraft** [comment] 2022-07-02 12:29
Wanted to add on to this. It's still happening. Still resets the music. Android 12 Samsung a52 5g

https://imgur.com/a/qo4p0F7

**Comment by enricocid** [comment] 2022-07-02 14:30
Thanks, unfortunately I can't test this behaviour on Android 12 / Samsung, but I will send some test APK once migration to material 3 is finished. Gonna try to fix in the next release. Thank You.

**Comment by cardcraft** [comment] 2022-07-02 19:05
Alright! I'm willing to test

**Comment by twisteros** [comment] 2022-07-05 07:18
I've clarified steps in the first post and added some screenshots. Hopefully it will help to reproduce the issue.

**Comment by enricocid** [comment] 2022-07-09 19:42
Are playback info & /time getting restored properly? :)

Dialogs and tabs not, right?

**Comment by cardcraft** [comment] 2022-07-09 19:51
Nope everything gets reset. The music restarts and everything

**Comment by enricocid** [comment] 2022-07-09 19:55
Ok, gonna try to fix this issue within the next few days. Thanks for the reply :)

**Comment by cardcraft** [comment] 2022-07-09 19:56
Ok! If you need ill test on my phone

**Comment by enricocid** [comment] 2022-07-09 19:58
In the meantime you can try the latest build. There's was a minor change affecting rotation. Anyway I don't think it mitigates the issue.
https://github.com/enricocid/Music-Player-GO/actions/runs/2639669460

**Comment by enricocid** [comment] 2022-07-11 11:08
Will post a test APK tomorrow for the media player reset issue.😉

**Comment by enricocid** [comment] 2022-07-12 09:18
Test apk here:

https://drive.google.com/file/d/1CL6OWLMLE9vwcHKx9CBFHFvOSGOl4zbq/view?usp=sharing

I will be able to work on UI issues during the weekend, probably. Thanks

**Comment by enricocid** [comment] 2022-07-13 15:55
Second test apk. Applies to UI elements like tabs and details.

https://drive.google.com/file/d/1xXaRhvnP9rxitETQ6-4LFkWaLg9rv0Oq/view?usp=sharing

**Comment by cardcraft** [comment] 2022-07-13 15:58
The UI still has to load but the music doesn't restart anymore!

**Comment by enricocid** [comment] 2022-07-13 16:34
What about current tab? Is it getting restored? In my tests it works good. Let me know.

**Comment by twisteros** [comment] 2022-07-13 17:24
UI is working fine now

**Comment by cardcraft** [comment] 2022-07-13 18:16
The current tab stays but the little currently playing card popup doesn't. https://user-images.githubusercontent.com/61369184/178802915-583ec174-7860-4738-877f-fd48271f5bcf.mp4

**Comment by enricocid** [comment] 2022-07-13 19:10
Yeah, restoring now playing dialog is a bit tricky... Gonna post some test APK later :) thanks

**Comment by enricocid** [comment] 2022-07-14 16:16
Another test apk

https://drive.google.com/file/d/13S4mk_N7LaBBJtlDlh6I7RiHUqThe9Zi/view?usp=sharing

Now playing and queue dialogs should work fine now. :)

**Comment by enricocid** [comment] 2022-07-15 18:07
This issue should be fixed now. Let me know if there's still something I can do. If you want you can test the debug APK built by the GitHub action.

https://github.com/enricocid/Music-Player-GO/actions

Closing for now. Thanks.

**Closed by enricocid** 2022-07-15 18:07 UTC
Labels: bug

**Comment by enricocid** [comment] 2022-08-07 14:13
Had to revert some changes.
Only tab will be restored.
Restoring fragments/dialogs causes bad behaviours on certain devices. Will search for a more reliable solution later. Thanks
